simulation:
  t_start: 0.0
  t_step: 5.0
  bodies:
    - label: body1
      mass: 1.0
      position:
        - 0.0
        - 8378137.0
        - 0.0
      velocity:
        - 6900.0
        - 0.0
        - 0.0
    - label: Earth
      mass: 5.9722e24
      position:
        - 0.0
        - 0.0
        - 0.0
      velocity:
        - 0.0
        - 0.0
        - 0.0
      model: earth
models:
  earth:
    shape: sphere
    texture: images/earth.jpeg
