simulation:
  t_start: 0.0
  t_step: 200.0
  bodies:
    - label: Moon
      mass: 7.342e22
      diameter: 3476200.0
      position:
        - 0.0
        - 0.0
        - -405400000.0
      velocity:
        - 1022.0
        - 0.0
        - 0.0
      spin:
        tilt: 1.5424
        velocity: 0.001
        angle: 0.0
    - label: Earth
      mass: 5.9722e24
      diameter: 6378000.0
      position:
        - 0.0
        - 0.0
        - 0.0
      velocity:
        - 0.0
        - 0.0
        - 0.0
      spin:
        tilt: 23.439
        velocity: 7.2921150e-5
        angle: 0.0
models:
  earth:
    shape: sphere
    texture: images/earth.jpeg
    bodies:
      - Earth
  moon:
    shape: sphere
    texture: images/moon.jpeg
    bodies:
      - Moon
